export default {
    CELL_SIZE: 10,
    GRID_W: 160,
    GRID_H: 90,
    NEST_X: 80,
    NEST_Y: 45,
    ANTS: 50,
    FOOD: 50,
    FOOD_STOCK: 10,
    OBSTACLE_COUNT: 10,
    OBSTACLE_SIZE: 5,
    DELIVERY_MODE: "Delivery",
    SCAVENGER_MODE: "Scavenger",
    FRAMERATE: 60,
}
